config:
  request:
    iplimit:
      apis: /api/user/register/
      intervalMinutes: 1
      maxRequestCount: 6
  response:
    message:
      seeother: 您频繁进⾏注册，请求已被拒绝！
      unauthorize: 您的请求没有授权，请登录或注册后再访问！
  email:
    host: smtp.163.com
    sender:
      name: 15927030662@163.com
      password: WGNHSKUQKWRCICYA
      port: 
    templates:
      checkcode:
        title: 注册验证码
        content: 您好，本次登录的验证码为：%s，将在10分钟之后过期
  code:
    validate:
      expire: 600


